packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  '@better-auth/expo': 1.4.0-beta.9
  '@eslint/js': ^9.38.0
  '@tailwindcss/postcss': ^4.1.16
  '@tanstack/react-form': ^1.23.8
  '@types/node': ^22.18.12
  eslint: ^9.38.0
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  nextjs-react:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: 19.2.1
    react-dom: 19.2.1
  expo-react:
    '@types/react': ^19.1.12
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  '@types/minimatch': 5.1.2
  lightningcss: 1.30.1
  vite: 7.1.12

publicHoistPattern:
  - '@ianvs/prettier-plugin-sort-imports'
  - prettier-plugin-tailwindcss
